package haibao.com.api.data.param.activity;

/**
 * AutoGenerated RequestParam  */
public final class PostActivitiesRequestParam {


  /**
   * type= Integer  
   * description=<p>圈子的id</p>  
   * optional=false 
   */
  public Integer club_id;

  /**
   * type= String  
   * description=<p>活动主题，120字以内</p>  
   * optional=false 
   */
  public String title;

  /**
   * type= String  
   * description=<p>活动海报URL，上传图片后获得</p>  
   * optional=false 
   */
  public String cover;

  /**
   * type= Integer  
   * description=<p>活动开始时间，Unix时间</p>  
   * optional=false 
   */
  public Integer start_time;

  /**
   * type= Integer  
   * description=<p>活动结束时间，Unix时间</p>  
   * optional=false 
   */
  public Integer end_time;

  /**
   * type= Integer  
   * description=<p>活动最晚参与时间，Unix时间</p>  
   * optional=true 
   */
  public Integer latest_time;

  /**
   * type= Integer  
   * description=<p>是否线上活动，1线上，0线下</p>  
   * optional=false 
   */
  public Integer is_online;

  /**
   * type= Double  
   * description=<p>活动参与价格，默认0.00，即免费</p>  
   * optional=true 
   */
  public Double price;

  /**
   * type= String  
   * description=<p>定位获取所在省名称</p>  
   * optional=true 
   */
  public String province;

  /**
   * type= String  
   * description=<p>定位获取所在市名称</p>  
   * optional=true 
   */
  public String city;

  /**
   * type= String  
   * description=<p>定位获取所在区的名称</p>  
   * optional=true 
   */
  public String district;

  /**
   * type= String  
   * description=<p>定位后除去省市区的地址说明</p>  
   * optional=true 
   */
  public String address;

  /**
   * type= String  
   * description=<p>楼号，门牌号等</p>  
   * optional=true 
   */
  public String address_detail;

  /**
   * type= Double  
   * description=<p>定位的经度，精确到小数点后8位</p>  
   * optional=true 
   */
  public Double longitude;

  /**
   * type= Double  
   * description=<p>定位的纬度，精确到小数点后8位</p>  
   * optional=true 
   */
  public Double latitude;

  /**
   * type= Integer  
   * description=<p>关联商品的id</p>  
   * optional=true 
   */
  public Integer goods_id;

  /**
   * type= String  
   * description=<p>活动说明，不限制长度</p>  
   * optional=false 
   */
  public String content;
}
