package haibao.com.api.data.param.myclass;


/**
 * AutoGenerated RequestParam  */
public final class PostClubsClubIdClassesClassIdCoursesRequestParam {
  /**
   * type= Integer  
   * description=<p>课程id</p>  
   * optional=false 
   */
  public Integer course_id;
}
