package haibao.com.api.data.param.myclass;

/**
 * AutoGenerated RequestParam  */
public final class PutClubsClubIdClassesClassIdRequestParam {
  /**
   * type= String  
   * description=<p>班级名称，20字符以内</p>  
   * optional=true 
   */
  public String name;

  /**
   * type= String  
   * description=<p>班级海报的URL，通过图片上传接口获得</p>  
   * optional=true 
   */
  public String cover;

  /**
   * type= Integer  
   * description=<p>班主任id，默认为推广人的user_id</p>  
   * optional=true 
   */
  public Integer master_id;

  /**
   * type= Integer  
   * description=<p>相关书单的id，书单来至童书馆</p>  
   * optional=true 
   */
  public Integer booklist_id;

  /**
   * type= String  
   * description=<p>班级简介，不限制长度</p>  
   * optional=true 
   */
  public String class_desc;

  /**
   * type= Integer  
   * description=<p>班级对应的频道id</p>  
   * optional=true 
   */
  public Integer channel_id;
}
