package haibao.com.api.data.param.club;

import java.lang.Integer;

/**
 * AutoGenerated RequestParam  */
public final class PutClubsClubIdMessagesUnreadRequestParam {
  /**
   * type= Integer  
   * description=<p>设置我的班级未读消息数，请求时设为0</p>  
   * optional=true 
   */
  public Integer class_unread_number;

  /**
   * type= Integer  
   * description=<p>设置阅读活动未读消息数，请求时设为0</p>  
   * optional=true 
   */
  public Integer activity_unread_number;
}
