package haibao.com.api.data.param.favorite;

/**
 * AutoGenerated RequestParam  */
public  class PostFavoritesRequestParam {
  /**
   * type= Integer  
   * description=<p>类型，1表示内容，2表示商品</p>  
   * optional=false 
   */
  public Integer favorite_type;

  /**
   * type= Integer  
   * description=<p>类型id，比如商品时为goods_id</p>  
   * optional=false 
   */
  public Integer favorite_type_id;
}
