package haibao.com.api.data.param.collection;

import java.util.ArrayList;

/**
 * AutoGenerated RequestParam  */
public final class DeleteCollectionsBatchRequestParam {
  /**
   * type= Array  
   * description=<p>收藏的id</p>  
   * optional=false 
   */
  public ArrayList collection_ids;
}
