package haibao.com.api.data.param.collection;

import java.lang.Integer;

/**
 * AutoGenerated RequestParam  */
public final class PostCollectionsRequestParam {
  /**
   * type= Integer  
   * description=<p>类型，1表示日记，2表示商品</p>  
   * optional=false 
   */
  public Integer collection_type;

  /**
   * type= Integer  
   * description=<p>类型id，比如商品时为goods_id</p>  
   * optional=false 
   */
  public Integer collection_type_id;
}
