package haibao.com.api.data.param.content;

import java.io.Serializable;
import java.lang.Integer;
import java.lang.String;

/**
 * AutoGenerated RequestParam
 */
public class CommentsRequestParam implements Serializable {
    public String content;
    public String audio_url;
    public String audio_duration_format;
    public Integer to_user_id;
    public String to_comment_id;
}
