package haibao.com.api.data.param.content;

import java.lang.Integer;

/**
 * AutoGenerated RequestParam  */
public final class PutContentsContentIdRequestParam {
  /**
   * type= Integer  
   * description=<p>是否阅读圈可见，1可见，0不可见</p>  
   * optional=false 
   */
  public Integer is_open;
}
