package haibao.com.api.data.param.bookshelf;

/**
 * AutoGenerated RequestParam  */
public final class DeleteArchivesArchiveIdGoodsBatchRequestParam {
  /**
   * type= Integer[]  
   * description=<p>商品id数组</p>  
   * optional=false 
   */
  public Integer[] goods_ids;

  public DeleteArchivesArchiveIdGoodsBatchRequestParam(Integer[] mgoods_ids) {
    goods_ids=mgoods_ids;
  }
}
