package haibao.com.api.data.param.bookshelf;

/**
 * AutoGenerated RequestParam  */
public final class PostArchivesArchiveIdGoodsRequestParam {
  /**
   * type= Integer  
   * description=<p>商品的id</p>  
   * optional=false 
   */
  public Integer[] goods_ids;

  public PostArchivesArchiveIdGoodsRequestParam(Integer[] mgoods_ids) {
    goods_ids=mgoods_ids;
  }
}
