package haibao.com.api.data.param.bookshelf;

import java.lang.String;

/**
 * AutoGenerated RequestParam  */
public class PostArchivesRequestParam {
  /**
   * type= String  
   * description=<p>分组名，15个字符以内</p>  
   * optional=false 
   */
  private String archive_name;
  public PostArchivesRequestParam(String marchive_name){
    archive_name=marchive_name;
  }
}
