package haibao.com.api.data.param.bookshelf;

import java.lang.String;

/**
 * AutoGenerated RequestParam  */
public final class PutArchivesArchiveIdRequestParam {
  /**
   * type= String  
   * description=<p>分组名称，15个字符以内</p>  
   * optional=false 
   */
  public String archive_name;

  public PutArchivesArchiveIdRequestParam(String name){
    archive_name=name;
  }
}
