package haibao.com.api.data.param.course;

/**
 * AutoGenerated RequestParam  */
public final class PostCoursesCourseIdCoursewareRequestParam {
  /**
   * type= String  
   * description=<p>课件类型，1图片，2视频</p>  
   * optional=false 
   */
  public Integer type;

  /**
   * type= Integer  
   * description=<p>课件顺序</p>  
   * optional=false 
   */
  public Integer order_num;

  /**
   * type= String  
   * description=<p>课件地址，图片通过接口上传获得，视频通过OSS上传获得</p>  
   * optional=false 
   */
  public String url;

  public String video_cover;
}
