package haibao.com.api.data.param.course;

/**
 * AutoGenerated RequestParam
 */
public final class PutCoursesCourseIdLiveRequestParam {
    /**
     * type= Integer
     * description=<p>直播状态，1结束直播，2未开始，3开始直播</p>
     * optional=false
     */
    public Integer live_status;

    public PutCoursesCourseIdLiveRequestParam() {
    }

    public PutCoursesCourseIdLiveRequestParam(Integer live_status) {
        this.live_status = live_status;
    }
}
