package haibao.com.api.data.param.course;

/**
 * AutoGenerated RequestParam
 */
public final class PutCoursesCourseIdCoursewareBatchRequestParam {
    /**
     * type= Integer
     * description=<p>课件的id</p>
     * optional=false
     */
    public Integer courseware_id;

    /**
     * type= String
     * description=<p>课件类型，1图片，2视频</p>
     * optional=true
     */
    public Integer type;

    /**
     * type= Integer
     * description=<p>课件顺序</p>
     * optional=true
     */
    public Integer order_num;

    /**
     * type= String
     * description=<p>课件地址，图片通过接口上传获得，视频通过OSS上传获得</p>
     * optional=true
     */
    public String url;
    /**
     * 视频课件cover
     */
    public String video_cover;
}
