package haibao.com.api.data.param.course;

/**
 * AutoGenerated RequestParam
 */
public final class PutCoursesCourseIdVideoRequestParam {
    /**
     * video_url	String
     视频地址

     video_cover 可选	String
     视频cover地址，不传时取第一个课件的cover

     video_duration_format	String
     视频时长，格式：HH:mm:ss

     video_size	Float
     视频大小(M)，保留三位小数

     video_width	Integer
     视频宽度

     video_height	Integer
     视频高度
     */
    public String video_url;
    public String video_cover;
    public String video_duration_format;
    public float video_size;
    public Integer video_width;
    public Integer video_height;


}
