package haibao.com.api.data.param.course;

import java.lang.Integer;
import java.lang.String;

/**
 * AutoGenerated RequestParam  */
public final class PutCoursesCourseIdRequestParam {
  /**
   * type= String  
   * description=<p>课程主题，120字符以内</p>  
   * optional=true 
   */
  public String title;

  /**
   * type= String  
   * description=<p>课程海报的URL，通过图片上传接口获得</p>  
   * optional=true 
   */
  public String cover;

  /**
   * type= Integer  
   * description=<p>直播时间，Unix时间</p>  
   * optional=true 
   */
  public Integer live_time;

  /**
   * type= Integer  
   * description=<p>预计直播结束时间，Unix时间</p>  
   * optional=true 
   */
  public Integer live_end_time;

  /**
   * type= Integer  
   * description=<p>直播类型，1白板直播，2视频直播，默认1</p>  
   * optional=true 
   */
  public Integer live_type;

  /**
   * type= Integer  
   * description=<p>讲师id，即讲师的user_id</p>  
   * optional=true 
   */
  public Integer lecturer_id;

  /**
   * type= String  
   * description=<p>课程简介，不限制长度</p>  
   * optional=true 
   */
  public String course_desc;

  /**
   * type= Integer  
   * description=<p>课程所属的频道id</p>  
   * optional=true 
   */
  public Integer channel_id;

  /**
   * type= Integer  
   * description=<p>相关童书id</p>  
   * optional=true 
   */
  public Integer goods_id;

  /**
   * type= String  
   * description=<p>课件格式，取值为43或169</p>  
   * optional=true 
   */
  public String courseware_format;
}
