package haibao.com.api.data.param.offline;

import java.util.List;

/**
 * AutoGenerated RequestParam
 */
public final class DeleteOfflinelistBatchRequestParam {

    /**
     * type= Integer[]
     * description=<p>离线对象id数组</p>
     * optional=false
     */
    public List<Integer> offline_ids;

}
