package haibao.com.api.data.param.offline;

/**
 * AutoGenerated RequestParam
 */
public final class OfflinelistRequestParam {
    /**
     * type= Integer
     * description=<p>来源，1内容content，2课程小节section，3图书isbn，4课程course</p>
     * optional=false
     */
    public Integer source_form;

    /**
     * type= Integer
     * description=<p>来源的id，比如内容时为content_id，课程小节时为section_id，图书时为isbn_id，课程时为course_id</p>
     * optional=false
     */
    public Integer source_type_id;

    /**
     * type= Integer
     * description=<p>资源id，来源为课程小节和图书时需传递相应资源的ID</p>
     * optional=true
     */
    public Integer resource_id;
}
