package haibao.com.api.data.param.chat;

import java.util.ArrayList;

/**
 * AutoGenerated RequestParam
 */
public final class ChatGroupsGroupIdUsersRequestParam {
    /**
     * type= Integer
     * description=<p>用户id数组,比如[12,13,34]</p>
     * optional=false
     */
    public ArrayList<Integer> user_ids;

    public ChatGroupsGroupIdUsersRequestParam() {
    }


}
