package haibao.com.api.data.param.chat;

import java.util.ArrayList;

/**
 * AutoGenerated RequestParam  */
public final class PostChatGroupsRequestParam {
  /**
   * type= String  
   * description=<p>群名称，20字符以内</p>  
   * optional=false 
   */
  public String name;

  /**
   * type= String  
   * description=<p>群头像，为空时采用最先加入的用户头像生成</p>  
   * optional=true 
   */
  public String avatar;

  /**
   * type= String  
   * description=<p>群公告，1000字符以内</p>  
   * optional=true 
   */
  public String announcement;

  /**
   * type= Array  
   * description=<p>群成员的user_id列表，比如 [124,423,235]</p>  
   * optional=false 
   */
  public ArrayList<Integer> user_ids;

  public PostChatGroupsRequestParam() {
  }

  public PostChatGroupsRequestParam(String name, String avatar, String announcement, ArrayList<Integer> user_ids) {
    this.name = name;
    this.avatar = avatar;
    this.announcement = announcement;
    this.user_ids = user_ids;
  }
}
