package haibao.com.api.data.param.chat;

import java.lang.String;

/**
 * AutoGenerated RequestParam  */
public final class PutChatGroupsGroupIdRequestParam {
  /**
   * type= String  
   * description=<p>群名称，20字符以内</p>  
   * optional=true 
   */
  public String name;

  /**
   * type= String  
   * description=<p>群头像，为空时采用最先加入的用户头像生成</p>  
   * optional=true 
   */
  public String avatar;

  /**
   * type= String  
   * description=<p>群公告，1000字符以内</p>  
   * optional=true 
   */
  public String announcement;
}
